on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 
      - dev/**

name: On Push To Dev Workspace Only Main Branch with Review to Apply

jobs:
  TF_PLAN:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: Dev Plan
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VERSION: ">=0.12"
      TF_WORKSPACE: dev
    outputs:
      TF_PLAN_SHA: ${{ github.sha }}

    defaults:
      run:
        shell: bash
        working-directory: ./dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: |
          terraform init

      - name: Terraform List Workspace
        id: workspace-list
        run: terraform workspace list
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -out=${{ github.sha }}.tfplan

      - name: Upload Terraform Plan Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.sha }}
          path: dev/${{ github.sha }}.tfplan
          if-no-files-found: error
        
  TF_APPLY:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: Dev Apply
    needs: TF_PLAN
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VERSION: ">=0.12"
      TF_WORKSPACE: dev

    defaults:
      run:
        shell: bash

    steps:          
      - name: Download Terraform Plan Artifact
        id: download
        uses: actions/download-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: terraform-plan-${{ needs.TF_PLAN.outputs.TF_PLAN_SHA }}
          path: terraform-plan-${{ needs.TF_PLAN.outputs.TF_PLAN_SHA }}.tfplan
  
      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main'
        run: |
          ls
          terraform apply -auto-approve -input=false terraform-plan-${{ needs.TF_PLAN.outputs.TF_PLAN_SHA }}.tfplan


        # On push to "main", build or change infrastructure according to Terraform configuration files
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main'
      #   run: terraform apply -auto-approve -input=false
